# トップに表示するrails version系列
rails_releases:
  -
    major: 3
    minor:
  -
    major: 4
    minor: 1
  -
    major: 4
    minor: 2
  -
    major: 5
    minor:

# projectをcloneする際の置き場
path:
  working_directory: "tmp/projects/<%= Rails.env %>"

feeds:
  rubygem:           "https://rubygems.org/gems/"
  ruby_security_ann: "https://groups.google.com/forum/feed/ruby-security-ann/topics/atom.xml?num=50"
  rubyonrails_security: "https://groups.google.com/forum/feed/rubyonrails-security/topics/atom.xml?num=50"
