# トップに表示するrails version系列
rails_releases:
  -
    major: 3
    min_minor: 2 # rails3.2...3.9系まで表示する
    max_minor: 9
  -
    major: 4
    min_minor: 1 # rails4.1...4.9系まで表示する
    max_minor: 9
  -
    major: 5
    min_minor: 0 # rails5.0...5.9系まで表示する
    max_minor: 9
  # rails5.0より大きいメジャーバージョンは、x.0..x.9まで表示する

# projectをcloneする際の置き場
path:
  working_directory: "tmp/projects/<%= Rails.env %>"

feeds:
  rubygem:           "https://rubygems.org/gems/"
  ruby_security_ann: "https://groups.google.com/forum/feed/ruby-security-ann/topics/atom.xml?num=50"
  rubyonrails_security: "https://groups.google.com/forum/feed/rubyonrails-security/topics/atom.xml?num=50"
