# トップに表示するrails version系列
rails_releases:
  -
    major: 3
    minor: #指定がない場合は最も大きいバージョン
  -
    major: 4
    minor: 1 # rails4.1...4.9系まで表示する
  -
    major: 5
    minor: #指定がない場合は最も大きいバージョン
  # rails5.0より大きいメジャーバージョンは、x.0..x.9まで表示する

# projectをcloneする際の置き場
path:
  working_directory: "tmp/projects/<%= Rails.env %>"

feeds:
  rubygem:           "https://rubygems.org/gems/"
  ruby_security_ann: "https://groups.google.com/forum/feed/ruby-security-ann/topics/atom.xml?num=50"
  rubyonrails_security: "https://groups.google.com/forum/feed/rubyonrails-security/topics/atom.xml?num=50"

links:
  cve: "http://cve.mitre.org/cgi-bin/cvename.cgi?name="
  jvn: "http://jvndb.jvn.jp/search/index.php?mode=_vulnerability_search_IA_VulnSearch&lang=ja&keyword="
  osvdb: "http://osvdb.org/show/osvdb/"
  rubysec: "http://rubysec.com/advisories/"
git:
  ruby_advisory_db: 'https://github.com/rubysec/ruby-advisory-db.git'


